/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunargp4.view;

import java.util.ArrayList;
import java.util.List;
import vacunargp4.modelo.*;
import vacunargp4.control.*;

/**
 *
 * @author bebo_
 */
public class viewCentroVacunacion extends javax.swing.JInternalFrame {
    VacunatorioData vd;
    List<String> departamentos = new ArrayList<>();
    
String depAya[] = new String[]{
    "Candelaria",
    "La Majada",
    "Leandro N. Alem",
    "Luján",
    "Quines",
    "Río Juan Gómez",
    "San Francisco del Monte de Oro"};
    
    String depPuey[] = new String[]{
    "San Luis (capital provincial)",
    "Alto Pencoso",
    "Balde", 
    "Beazley",
    "Cazador",
    "Chosmes",
    "Desaguadero",
    "El Volcán",
    "Jarilla",
    "Juana Koslay", 
    "La Punta",
    "Mosmota",
    "Potrero de los Funes",
    "Salinas del Bebedero",
    "San Gerónimo",
    "Zanjitas"};
    
    String depBel[] = new String[]{
     "La Calera ",
    "Nogolí "  ,
    "Villa de la Quebrada "  ,
    "Villa General Roca"  
    };
    String depCha[] = new String[]{
        "Concarán",
"Cortaderas",
"Naschel",
"Papagayos",
"Renca",
"San Pablo",
"Tilisarao",
"Villa del Carmen",
"Villa Larca"
    };
    String depPeder[] = new String[]{
        "Juan Jorba",
    "Juan Llerena",
    "Justo Daract",
    "La Esquina",
    "La Punilla",
    "Lavaisse",
    "San José del Morro",
    "Villa Mercedes"
    };
    String depPrin[] = new String[]{
        "Carolina",
"El Trapiche",
"Fraga",
"La Bajada",
"La Florida",
"La Toma",
"Riocito",
"Saladillo",
"Estancia Grande"
    };
    String depJuj[] = new String[]{
        "Carpintería",
"Cerro de Oro",
"Lafinur",
"Los Cajones",
"Los Molles",
"Merlo",
"Santa Rosa de Conlara",
"Talita"
    };
    String depDup[] = new String[]{
      "Anchorena",
"Arizona",
"Bagual",
"Batavia",
"Buena Esperanza",
"Fortín El Patria",
"Fortuna",
"La Maroma",
"Martín de Loyola",
"Nahuel Mapá",
"Navia",
"Nueva Galia",
"Unión"  
    };
    String depMart[] = new String[]{
      "Anchorena",
"Arizona",
"Bagual",
"Batavia",
"Buena Esperanza",
"Fortín El Patria",
"Fortuna",
"La Maroma",
"Martín de Loyola",
"Nahuel Mapá",
"Navia",
"Nueva Galia",
"Unión"  
    };
    public viewCentroVacunacion(VacunatorioData vd) {
        initComponents();
        this.vd = vd;
        departamentos.add("Ayacucho");
        departamentos.add("Belgrano");
        departamentos.add("Chacabuco");
        departamentos.add("Coronel Pringles");
        departamentos.add("General Pedernera");
        departamentos.add("Gobernador Dupuy");
        departamentos.add("Junín");
        departamentos.add("Pueyrredón");
        departamentos.add("Libertador General San Martín");
        llenarDepartamentos();
    }
    void llenarDepartamentos(){
        for(String i:departamentos){
            jcbDepartamento.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jcbDepartamento = new javax.swing.JComboBox<>();
        jcbCiudad = new javax.swing.JComboBox<>();
        jbRegistrar = new javax.swing.JButton();

        jLabel1.setText("Centro de Vacunacion vacunAr 2001");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Departamento:");

        jLabel4.setText("Ciudad:");

        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jcbDepartamento.setToolTipText("");
        jcbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDepartamentoActionPerformed(evt);
            }
        });

        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(jtfNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54)
                                .addComponent(jcbCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRegistrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jcbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jbRegistrar)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jcbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDepartamentoActionPerformed
        switch((String)jcbDepartamento.getSelectedItem()){
            case "Pueyrredón":
                jcbCiudad.removeAllItems();
                for(String j:depPuey){
               jcbCiudad.addItem(j);
                }
                break;
            case "Belgrano":
                jcbCiudad.removeAllItems();
                for(String b:depBel){
                    jcbCiudad.addItem(b);
                }
                break;
            case "Ayacucho":
                jcbCiudad.removeAllItems();
                for(String a:depAya){
                    jcbCiudad.addItem(a);
                }
                break;
            case "Chacabuco":
                jcbCiudad.removeAllItems();
                for(String c:depCha){
                    jcbCiudad.addItem(c);
                }
                break;
            case "Coronel Pringles":
                jcbCiudad.removeAllItems();
                for(String cp:depPrin){
                    jcbCiudad.addItem(cp);
                }
                break;
            case "Coronel Pedernera":
                jcbCiudad.removeAllItems();
                for(String cs:depPrin){
                    jcbCiudad.addItem(cs);
                }
                break;
            case "Gobernador Dupuy":
                jcbCiudad.removeAllItems();
                for(String d:depDup){
                    jcbCiudad.addItem(d);
                }
                break;
            case "Junín":
                jcbCiudad.removeAllItems();
                for(String j:depJuj){
                    jcbCiudad.addItem(j);
                }
                break;
            case "Libertador General San Martín":
                jcbCiudad.removeAllItems();
                for(String san:depMart){
                    jcbCiudad.addItem(san);
                }
        }
    }//GEN-LAST:event_jcbDepartamentoActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        String ciudad = (String)jcbCiudad.getSelectedItem();
        String dep = (String)jcbDepartamento.getSelectedItem();
        String nombre = jtfNombre.getText();
        Vacunatorio vac = new Vacunatorio(nombre, dep, nombre);
        vd.crearVacunatorio(vac);
        
    }//GEN-LAST:event_jbRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JComboBox<String> jcbDepartamento;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
